services:
  fastapi:
    container_name: coffe_fastapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:8009"
    environment:
      - DATABASE_URL=postgresql://postgres:1111@db:5432/coffe
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: coffe
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
