services:
  fastapi:
    container_name: coffe_fastapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:8009"
    environment:
      - DATABASE_URL=postgresql://postgres:1111@db:5432/cafeteria
      - USERNAME=admin
      - PASSWORD=RA2204i
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: coffe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: coffe_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    external: true
