services:
  fastapi:
    container_name: cafeteria_fastapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8008"
    depends_on:
      - postgresql
      - redis
    command: bash -c "alembic upgrade head && gunicorn -b 0.0.0.0:8008 -w 4 -t 360 -k uvicorn.workers.UvicornWorker main:app --max-requests 250 --max-requests-jitter 50 --access-logfile -"
    environment:
      APP_TITLE: "Cafeteria"
      POSTGRES_URL: postgresql+psycopg2://admin:admin@postgresql:5432/cafeteria_db
      USERNAME: SakuraMidori
      PASSWORD: Ramen#1234
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: my_super_secret_key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    networks:
      - cafeteria-network

  postgresql:
    container_name: cafeteria_postgresql
    command: postgres -c 'max_connections=500'
    image: postgres:16
    hostname: postgresql
    ports:
      - "5439:5432"
    volumes:
      - ./db_volume:/var/lib/postgresql/data/
    labels:
      - "traefik.enable=false"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cafeteria_db
      TZ: Asia/Tashkent
    networks:
      - cafeteria-network

  redis:
    container_name: cafeteria_redis
    image: "redis:alpine"
    labels:
      - "traefik.enable=false"
    ports:
      - "6378:6379"
    volumes:
      - cache:/data
    hostname: redis
    command: redis-server
    networks:
      - cafeteria-network

volumes:
  postgres_data:
  cache:

networks:
  cafeteria-network:
    name: cafeteria-network
    external: true
