"""empty message

Revision ID: a9dc80317aeb
Revises: 3617b232bb26
Create Date: 2024-11-04 14:40:37.134282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9dc80317aeb'
down_revision: Union[str, None] = '3617b232bb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coffee', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('coffee', 'harvest_date')
    op.drop_column('coffee', 'reviews_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffee', sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coffee', sa.Column('harvest_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('coffee', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
