"""empty message

Revision ID: 2214abe71230
Revises: 33766e5c6052
Create Date: 2024-11-04 09:27:15.821867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2214abe71230'
down_revision: Union[str, None] = '33766e5c6052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coffee_id', table_name='coffee')
    op.drop_table('coffee')
    op.add_column('menu', sa.Column('product', sa.String(), nullable=False))
    op.add_column('menu', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('flavor_profile', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('bean_type', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('menu', sa.Column('rating', sa.Float(), nullable=True))
    op.alter_column('menu', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('menu', 'description')
    op.drop_column('menu', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('menu', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('menu', 'rating')
    op.drop_column('menu', 'stock')
    op.drop_column('menu', 'bean_type')
    op.drop_column('menu', 'flavor_profile')
    op.drop_column('menu', 'origin')
    op.drop_column('menu', 'product')
    op.create_table('coffee',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('flavor_profile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bean_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('harvest_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], name='coffee_menu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='coffee_pkey')
    )
    op.create_index('ix_coffee_id', 'coffee', ['id'], unique=False)
    # ### end Alembic commands ###
