"""empty message

Revision ID: dfd05564b926
Revises: d762caf5224a
Create Date: 2024-10-31 11:56:12.085893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd05564b926'
down_revision: Union[str, None] = 'd762caf5224a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.String(), nullable=False))
    op.add_column('admin', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'admin', ['username'])
    op.drop_column('admin', 'hashed_password')
    op.drop_column('admin', 'name')
    op.add_column('client', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('client', 'name')
    op.add_column('company', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('company', 'name')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('company', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('company', 'username')
    op.add_column('client', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('client', 'username')
    op.add_column('admin', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('admin', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admin', type_='unique')
    op.drop_column('admin', 'password')
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###
