"""empty message

Revision ID: 24fe68d8f457
Revises: c89bbb155a3d
Create Date: 2024-11-01 18:21:06.346484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fe68d8f457'
down_revision: Union[str, None] = 'c89bbb155a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('password', sa.String(), nullable=False))
    op.add_column('client', sa.Column('logo', sa.String(), nullable=True))
    op.drop_column('client', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'logo')
    op.drop_column('client', 'password')
    # ### end Alembic commands ###
