"""empty message

Revision ID: 258b264b42f4
Revises: a7a7946ebf3b
Create Date: 2024-10-31 12:53:33.304622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258b264b42f4'
down_revision: Union[str, None] = 'a7a7946ebf3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'hashed_password')
    # ### end Alembic commands ###
