"""empty message

Revision ID: e510c7d58e77
Revises: d0216d4a17f7
Create Date: 2025-05-13 17:23:53.594877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e510c7d58e77'
down_revision: Union[str, None] = 'd0216d4a17f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('verification_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
